// Generates AUTHORIZATION_MATRIX.md, re-scanning with helper-aware auth detection.
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '../../..');
const DIR = path.resolve(__dirname, '..');

function walk(d, acc = []) {
  if (!fs.existsSync(d)) return acc;
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) { if (!['node_modules', '.next', '.git'].includes(e.name)) walk(p, acc); }
    else if (/\.(ts|tsx)$/.test(e.name)) acc.push(p);
  }
  return acc;
}
const routes = walk(path.join(ROOT, 'app/api')).filter(f => /route\.ts$/.test(f));

// helpers that themselves perform auth.getUser()
const AUTH_HELPERS = ['resolveSpotlightProfile', 'isAdmin', 'requireUser', 'getCreatorProfile'];

function url(f) {
  return '/' + path.relative(path.join(ROOT, 'app'), f).replace(/\\/g, '/')
    .replace(/\/route\.ts$/, '').replace(/\((?:[^)]+)\)\//g, '');
}

const rows = [];
for (const f of routes) {
  const src = fs.readFileSync(f, 'utf8');
  const rel = path.relative(ROOT, f).replace(/\\/g, '/');
  const methods = [...src.matchAll(/export\s+async\s+function\s+(GET|POST|PUT|PATCH|DELETE)/g)].map(m => m[1]);

  const getUser = /auth\.getUser\s*\(/.test(src);
  const getSession = /auth\.getSession\s*\(/.test(src);
  const helper = AUTH_HELPERS.find(h => new RegExp('\\b' + h + '\\s*\\(').test(src));
  const isAdminFn = /\bisAdmin\s*\(/.test(src);
  const service = /createServiceClient\s*\(/.test(src);
  const cron = /CRON_SECRET|x-cron-secret/i.test(src);
  const sig = /verifyWebhook|verifyStripeSignature|WEBHOOK_SECRET|createHmac/.test(src);
  const writes = /\.(insert|update|upsert|delete)\s*\(/.test(src);

  let auth = [];
  if (sig) auth.push('webhook signature/secret');
  if (cron) auth.push('CRON_SECRET bearer');
  if (isAdminFn) auth.push('isAdmin()');
  if (getUser) auth.push('getUser()');
  else if (helper) auth.push(`getUser() via ${helper}()`);
  else if (getSession) auth.push('getSession()');
  if (!auth.length) auth.push('**NONE**');

  // ownership scoping
  const ownership = [];
  if (/\.eq\(\s*["']user_id["']\s*,\s*user\.id/.test(src)) ownership.push('user_id = session user');
  if (/\.eq\(\s*["']fan_user_id["']\s*,\s*(user\.id|uid)/.test(src)) ownership.push('fan_user_id = session user');
  if (/\.eq\(\s*["']creator_profile_id["']\s*,\s*profile\.id/.test(src)) ownership.push('creator_profile_id = own profile');
  if (helper === 'resolveSpotlightProfile') ownership.push('own spotlight profile');
  if (isAdminFn || /\/admin\//.test(rel)) ownership.push('admin-wide');

  const rls = service ? 'BYPASSED (service role)' : 'enforced (anon client)';

  rows.push({ rel, url: url(f), methods, auth, ownership, rls, service, writes, sig, cron, isAdminFn, getUser, getSession, helper });
}

const out = [];
out.push('# Authorization Matrix (Phase 3)');
out.push('');
out.push('Every API route handler: authentication method, authorization check, ownership scoping,');
out.push('and whether RLS applies. Generated by `_tools/gen-authz.js`, then manually adjudicated —');
out.push('the scanner is helper-aware (`resolveSpotlightProfile()` performs `getUser()` internally),');
out.push('so routes that authenticate through a helper are **not** reported as unauthenticated.');
out.push('');
out.push('**Key.** *RLS bypassed* is not a defect by itself — it is correct for webhooks, cron and');
out.push('admin paths. It is a defect when it is not paired with a gate. `lib/supabase-server.ts`');
out.push('`createClient()` is the anon, RLS-enforced client; `createServiceClient()` bypasses RLS.');
out.push('');
out.push('| Route | Methods | Authentication | Authorization / ownership | RLS | Writes | Verdict |');
out.push('|---|---|---|---|---|---|---|');

const VERDICT = {
  'app/api/referrals/creator/route.ts': '🔴 **SL-005** unauthenticated, service role, issues $29 credits',
  'app/api/referrals/subscriber/route.ts': '🔴 unauthenticated, service role, forges referral rows (SL-043)',
  'app/api/referrals/attribute/route.ts': '🟠 unauthenticated; RPC has self/dup guards so impact is limited',
  'app/api/download/[token]/route.ts': '🔴 **SL-004** unauth, service role, all 3 guards disabled',
  'app/api/digital/download/route.ts': '🟡 unauth by design (token is the credential); token never expires',
  'app/api/claim/route.ts': '🟢 unauth by design; atomic single-use claim, format-validated. Well built',
  'app/api/webhooks/stripe/route.ts': '🔴 **SL-006** signature verified but no replay window',
  'app/api/webhooks/printful/route.ts': '🟠 **SL-040** secret in query string; keyed off own order id',
  'app/api/webhooks/auth/route.ts': '🟢 SUPABASE_WEBHOOK_SECRET header, fails closed',
  'app/api/webhooks/ccbill/route.ts': '🟡 verify signature handling against CCBill docs',
  'app/api/cron/billing-dunning/route.ts': '🟠 **SL-039** fails open if CRON_SECRET unset',
  'app/api/cron/live-billing/route.ts': '🟠 **SL-039** fails open if CRON_SECRET unset',
  'app/api/cron/publish-scheduled/route.ts': '🟠 **SL-039** fails open if CRON_SECRET unset',
  'app/api/social-posts/route.ts': '🟠 **SL-062** getSession() not getUser()',
  'app/api/admin/new-creator-alert/route.ts': '🟢 own-profile + 10-minute freshness replay guard',
  'app/api/tip/route.ts': '🟠 **SL-022** notifies creator before payment; unauthenticated by design',
  'app/api/unsubscribe/route.ts': '🟢 unauth by design; HMAC-signed token (lib/email.ts)',
  'app/api/account/delete/route.ts': '🟢 getUser() then service role scoped to that user',
  'app/api/fan/me/route.ts': '🟢 getUser(), all queries scoped to session user (queries broken — SL-016)',
  'app/api/analytics/route.ts': '🟢 getUser() + own profile; plan cap enforced server-side',
  'app/api/referrals/stats/route.ts': '🟢 getUser() + own profile',
  'app/api/referrals/me/route.ts': '🟢 getUser(), passes user.id to RPC (but see SL-045 grant)',
  'app/api/referrals/verify/route.ts': '🟢 getUser(), passes user.id to RPC (but see SL-045 grant)',
  'app/api/merch/route.ts': '🟢 public catalogue read, no sensitive columns',
  'app/api/search/route.ts': '🟢 public search, no sensitive columns',
};

for (const r of rows.sort((a, b) => a.url.localeCompare(b.url))) {
  let verdict = VERDICT[r.rel];
  if (!verdict) {
    if (r.auth[0] === '**NONE**' && r.writes) verdict = '🔴 unauthenticated write — review';
    else if (r.auth[0] === '**NONE**') verdict = '🟠 unauthenticated read — review';
    else if (r.service && !r.isAdminFn && !r.sig && !r.cron) verdict = '🟠 service role without an explicit gate';
    else verdict = '🟢 gated';
  }
  out.push('| `' + r.url + '` | ' + (r.methods.join(', ') || '—') + ' | ' + r.auth.join(' + ') + ' | ' +
    (r.ownership.join('; ') || '—') + ' | ' + r.rls + ' | ' + (r.writes ? 'yes' : 'no') + ' | ' + verdict + ' |');
}

out.push('');
out.push('---');
out.push('');
out.push('## Summary');
out.push('');
const noAuth = rows.filter(r => r.auth[0] === '**NONE**');
const svcNoGate = rows.filter(r => r.service && !r.isAdminFn && !r.sig && !r.cron && !r.getUser && !r.helper);
out.push('| Metric | Count |');
out.push('|---|---|');
out.push('| Route files | ' + rows.length + ' |');
out.push('| Handlers (method × route) | ' + rows.reduce((s, r) => s + r.methods.length, 0) + ' |');
out.push('| Uses `getUser()` directly or via helper | ' + rows.filter(r => r.getUser || r.helper).length + ' |');
out.push('| Uses `getSession()` only | ' + rows.filter(r => r.getSession && !r.getUser && !r.helper).length + ' |');
out.push('| Webhook signature / shared secret | ' + rows.filter(r => r.sig).length + ' |');
out.push('| CRON_SECRET gated | ' + rows.filter(r => r.cron).length + ' |');
out.push('| `isAdmin()` gated | ' + rows.filter(r => r.isAdminFn).length + ' |');
out.push('| Service role (RLS bypassed) | ' + rows.filter(r => r.service).length + ' |');
out.push('| **No authentication of any kind** | **' + noAuth.length + '** |');
out.push('');
fs.writeFileSync(path.join(DIR, '_authz_table.md'), out.join('\n'));
console.log('rows:', rows.length, 'noAuth:', noAuth.length);
console.log(noAuth.map(r => '  ' + r.url).join('\n'));
