// ──────────────────────────────────────────────────────────────────
// lib/niches.ts
// Creator niche data — marketing landing pages + onboarding guidance.
// To add a niche: add an entry to NICHES. Everything else is automatic.
// ──────────────────────────────────────────────────────────────────

export interface NicheFeature {
  icon: string;
  title: string;
  desc: string;
}

export interface Niche {
  slug: string;
  name: string;
  pageName: string;
  emoji: string;
  category: string; // for grouping in the picker
  headline: string;
  subhead: string;
  lede: string;
  pain: string;
  painDetail: string;
  features: NicheFeature[];
  earningExample: {
    scenario: string;
    them: { platform: string; take: string; youGet: string };
    us: { fee: string; youGet: string };
  };
  cta: string;
  metaTitle: string;
  metaDesc: string;
  // Onboarding guidance
  advisorContext: string; // Injected into AI advisor system prompt
  topFeatures: string[]; // 3 most relevant features to highlight in onboarding
}

const NICHES: Niche[] = [
  // ── Art & Design ──────────────────────────────────────────────
  {
    slug: "3d-designers",
    name: "3D Designers",
    pageName: "3D Print Designers",
    emoji: "🖨️",
    category: "Art & Design",
    headline: "Stop giving your STL files away for free.",
    subhead: "Your designs take hours. Your audience should pay for them.",
    lede: "You design for hours. You post to Cults3D, MyMiniFactory, Thingiverse. The downloads pile up. The money doesn't. Your most loyal followers want more — exclusive designs, early access, behind-the-scenes of your design process. Spotlightly is where they come to actually support you.",
    pain: "Cults3D / MyMiniFactory",
    painDetail: "Cults3D takes 8–20% of every sale. MyMiniFactory takes 10%. Your Patreon supporters pay monthly but have no real reason to stay. Your best fans download your free files and never come back.",
    features: [
      { icon: "📁", title: "Sell STL files directly", desc: "Upload any file — STL, 3MF, OBJ. Fans pay once, download instantly. 0% platform cut." },
      { icon: "🔒", title: "Exclusive subscriber designs", desc: "New designs drop for subscribers first — 30 days before they go public." },
      { icon: "🎥", title: "Design process content", desc: "CAD screen recordings, failed print compilations, material tests. Lock for subscribers." },
      { icon: "📡", title: "Live design sessions", desc: "Stream yourself designing in Fusion 360 or Blender. Subscribers watch live." },
      { icon: "🛍️", title: "Sell finished prints", desc: "List your physical prints in the marketplace. One-offs, custom runs, display pieces." },
      { icon: "💬", title: "Commission requests", desc: "Front Row messages let fans request custom designs. You set the terms." },
    ],
    earningExample: {
      scenario: "200 subscribers at $9.99/mo + 50 STL file sales at $4.99",
      them: { platform: "Cults3D + Patreon", take: "$598/mo in fees", youGet: "$2,247/mo" },
      us: { fee: "$79/mo flat", youGet: "$2,766/mo" },
    },
    cta: "Claim your designer handle",
    metaTitle: "Spotlightly for 3D Print Designers — Sell STL Files, Build Subscribers",
    metaDesc: "Stop giving away STL files for free. Sell your designs directly and keep 100% of digital sales. No Cults3D cut.",
    advisorContext: "This creator is a 3D print designer. Their top opportunities: selling STL/3MF files as digital products (0% cut), locking new designs for subscribers before public release, streaming design sessions live, and selling finished prints in the marketplace. Mention: Cults3D and MyMiniFactory take 8-20%. Here, digital downloads are 0% cut.",
    topFeatures: ["Digital Store (sell STL files — 0% cut)", "Exclusive subscriber content", "Live streaming design sessions"],
  },
  {
    slug: "artists",
    name: "Visual Artists",
    pageName: "Visual Artists & Illustrators",
    emoji: "🎨",
    category: "Art & Design",
    headline: "Instagram stole your audience. Take them back.",
    subhead: "Your work built their platform. Spotlightly builds yours.",
    lede: "You post your art. Instagram shows it to 6% of your followers. The algorithm buries your best work if it doesn't perform in the first hour. The people who genuinely love your art have no way to support you beyond a like. Spotlightly is where your real audience goes to actually invest in you.",
    pain: "Instagram / Redbubble",
    painDetail: "Redbubble takes 70-80% of each sale. Society6 takes 70%. Instagram organic reach has dropped to 5-8% for most artists. You're doing all the creative work and keeping almost nothing.",
    features: [
      { icon: "🖼️", title: "Sell prints & originals", desc: "Your art in the marketplace — prints, originals, commissions. 5% to Spotlightly, 95% to you." },
      { icon: "📁", title: "Digital downloads", desc: "Brushes, textures, reference packs, print-ready files. 0% platform cut." },
      { icon: "🔒", title: "Process content for subscribers", desc: "Speed paints, WIPs, timelapse recordings. The content that builds the deepest loyalty." },
      { icon: "📡", title: "Live drawing sessions", desc: "Stream your process. Subscribers watch, ask questions, commission pieces." },
      { icon: "🛍️", title: "Loudcap merch", desc: "Your illustrations on t-shirts, totes, posters, mugs. No upfront inventory." },
      { icon: "💬", title: "Commission requests", desc: "Fans pay to send priority commission requests." },
    ],
    earningExample: {
      scenario: "200 subscribers at $9.99/mo + $800/mo in print and digital sales",
      them: { platform: "Redbubble + Instagram", take: "Redbubble keeps 80% of sales", youGet: "$2,158/mo" },
      us: { fee: "$79/mo flat + 5% on sales", youGet: "$2,719/mo" },
    },
    cta: "Claim your artist handle",
    metaTitle: "Spotlightly for Artists — Sell Your Art Directly, Keep What You Earn",
    metaDesc: "Redbubble takes 80%. Spotlightly takes 5% on marketplace sales. Your art. Your audience. Your money.",
    advisorContext: "This creator is a visual artist or illustrator. Their top opportunities: selling prints and originals in the marketplace (5% cut), digital downloads like brushes and textures (0% cut), locking process videos for subscribers, and live drawing streams. Redbubble takes 70-80% — Spotlightly takes 5%.",
    topFeatures: ["Marketplace (prints & originals — 5% cut)", "Digital Store (brushes, files — 0% cut)", "Exclusive process content for subscribers"],
  },
  {
    slug: "photographers",
    name: "Photographers",
    pageName: "Photographers",
    emoji: "📷",
    category: "Art & Design",
    headline: "Your photos are worth more than stock licensing fees.",
    subhead: "Sell prints, presets, and exclusive shoots directly to fans who love your work.",
    lede: "You spend thousands on gear, hours on shoots, and hours more in post. Getty pays you $0.25 per download. Shutterstock pays fractions of a cent per use. Your Instagram followers love your work but have no way to buy it or support you. Spotlightly changes that.",
    pain: "Stock platforms / Instagram",
    painDetail: "Getty Images pays contributors 15-45% of licensing fees. Shutterstock pays $0.25–$0.38 per download at standard rates. Instagram has zero monetization for most photographers. You're the most underpaid creative on the internet.",
    features: [
      { icon: "🖼️", title: "Sell prints directly", desc: "Limited edition prints, signed prints, large format — straight from your page. 5% to Spotlightly." },
      { icon: "📁", title: "Sell presets & LUTs", desc: "Your editing style as a product. Fans pay once, download instantly. 0% cut." },
      { icon: "🔒", title: "Subscriber-only galleries", desc: "Behind-the-scenes shoots, unedited selects, location guides. Only for subscribers." },
      { icon: "🎥", title: "Editing process videos", desc: "Your Lightroom and Photoshop process locked for subscribers." },
      { icon: "📡", title: "Live shoots & critiques", desc: "Stream a shoot or a portfolio review. Subscribers only." },
      { icon: "💬", title: "Booking requests", desc: "Paid priority messages for session inquiries. You earn from the inquiry itself." },
    ],
    earningExample: {
      scenario: "150 subscribers at $12.99/mo + 100 preset pack sales at $29",
      them: { platform: "Getty + Instagram", take: "Getty keeps 55-85%. Instagram pays $0.", youGet: "$1,000/mo" },
      us: { fee: "$29/mo flat", youGet: "$4,828/mo" },
    },
    cta: "Claim your photography handle",
    metaTitle: "Spotlightly for Photographers — Sell Prints, Presets, and Exclusive Content",
    metaDesc: "Getty takes 55-85%. Instagram pays nothing. Sell prints and presets directly, build a subscriber base, and keep 100% of digital product sales.",
    advisorContext: "This creator is a photographer. Their top opportunities: selling presets and LUTs as digital downloads (0% cut), selling limited edition prints in the marketplace (5%), locking behind-the-scenes galleries and editing videos for subscribers. Mention: preset packs typically sell for $20-50 and convert well.",
    topFeatures: ["Digital Store (presets & LUTs — 0% cut)", "Marketplace (prints — 5% cut)", "Subscriber-only galleries"],
  },
  {
    slug: "graphic-designers",
    name: "Graphic Designers",
    pageName: "Graphic Designers",
    emoji: "✏️",
    category: "Art & Design",
    headline: "Your templates are worth more than one-time Etsy sales.",
    subhead: "Build recurring revenue from the design work you're already doing.",
    lede: "You make templates, mockups, fonts, icons, UI kits. You post on Creative Market, Etsy, Gumroad. Every sale is a one-time transaction. Your buyers come back — but they buy from the platform, not from you. Spotlightly gives you the relationship behind the product.",
    pain: "Creative Market / Etsy",
    painDetail: "Creative Market takes 30-40% of every sale. Etsy takes 6.5% transaction fee plus listing fees plus payment processing. Gumroad takes 10%. You're paying to be discovered by people who then don't follow you anywhere.",
    features: [
      { icon: "📁", title: "Sell design assets directly", desc: "Templates, mockups, fonts, icons, UI kits. 0% cut. Instant download." },
      { icon: "🔒", title: "Monthly asset drops for subscribers", desc: "New freebies or exclusive packs every month. Give subscribers a reason to stay." },
      { icon: "🎥", title: "Design tutorial content", desc: "Process videos, software tips, client workflow. Locked for paying subscribers." },
      { icon: "📡", title: "Live design critiques", desc: "Portfolio reviews, brief walkthroughs, live Q&A." },
      { icon: "🛍️", title: "Custom work marketplace", desc: "List your services or one-off pieces in the marketplace." },
      { icon: "💬", title: "Client inquiry messages", desc: "Paid priority messages for project inquiries." },
    ],
    earningExample: {
      scenario: "100 subscribers at $14.99/mo + 200 template sales at $19",
      them: { platform: "Creative Market", take: "Creative Market keeps 35%", youGet: "$2,295/mo" },
      us: { fee: "$29/mo flat", youGet: "$5,270/mo" },
    },
    cta: "Claim your design handle",
    metaTitle: "Spotlightly for Graphic Designers — Sell Templates, Build Subscribers",
    metaDesc: "Creative Market takes 35%. Spotlightly takes 0% on digital downloads. Sell your templates directly and build a recurring subscriber base.",
    advisorContext: "This creator is a graphic designer. Their top opportunities: selling design assets (templates, mockups, fonts) as digital downloads (0% cut), monthly exclusive asset drops for subscribers, and design tutorial content locked for subscribers.",
    topFeatures: ["Digital Store (assets — 0% cut)", "Exclusive monthly drops for subscribers", "Tutorial content"],
  },
  {
    slug: "cosplay",
    name: "Cosplayers",
    pageName: "Cosplayers & Costume Creators",
    emoji: "🦸",
    category: "Art & Design",
    headline: "Your builds deserve more than likes.",
    subhead: "Turn your craft into a career.",
    lede: "You spend hundreds of hours and thousands of dollars building costumes that blow people away. You post progress on Instagram and TikTok. The likes pile up. The money doesn't. Your most dedicated followers want patterns, tutorials, and exclusive content from you — and Spotlightly is where they come to pay for it.",
    pain: "Instagram / TikTok",
    painDetail: "TikTok pays $0.02-0.04 per 1,000 views. Instagram pays nothing. Your build videos go viral and you make $20. Meanwhile, your followers are asking for patterns, tutorials, and behind-the-scenes that you could be charging for.",
    features: [
      { icon: "📁", title: "Sell patterns & templates", desc: "Your build patterns as PDFs or cutting files. 0% cut. Instant download." },
      { icon: "🔒", title: "Build diaries for subscribers", desc: "Step-by-step content locked for your paying audience." },
      { icon: "📡", title: "Live build streams", desc: "Build with your community. Subscribers watch and ask questions." },
      { icon: "🛍️", title: "Sell finished pieces & props", desc: "One-off builds, props, accessories. Your marketplace, your prices." },
      { icon: "🎥", title: "Tutorial content", desc: "Worbla techniques, paint tutorials, wig styling — locked for subscribers." },
      { icon: "🧶", title: "Loudcap merch", desc: "Your branding on merch. No inventory. Ships worldwide." },
    ],
    earningExample: {
      scenario: "200 subscribers at $8.99/mo + 100 pattern sales at $12",
      them: { platform: "TikTok + Etsy", take: "TikTok pays $0.03/1k views. Etsy takes 6.5%.", youGet: "$2,922/mo" },
      us: { fee: "$79/mo flat", youGet: "$3,020/mo" },
    },
    cta: "Claim your cosplay handle",
    metaTitle: "Spotlightly for Cosplayers — Sell Patterns, Build Subscribers, Get Paid",
    metaDesc: "Your builds go viral and you make $20. Build a subscriber base, sell your patterns directly, and keep 100% of digital downloads.",
    advisorContext: "This creator is a cosplayer and costume builder. Their top opportunities: selling build patterns and templates (0% cut), exclusive build diaries for subscribers, live build streams, and selling finished pieces in the marketplace.",
    topFeatures: ["Digital Store (patterns — 0% cut)", "Exclusive build content for subscribers", "Marketplace (finished pieces)"],
  },

  // ── Commerce & Makers ─────────────────────────────────────────
  {
    slug: "etsy-sellers",
    name: "Etsy Sellers",
    pageName: "Etsy Sellers & Makers",
    emoji: "🧶",
    category: "Commerce & Makers",
    headline: "Etsy raised their fees again. Own your audience instead.",
    subhead: "Your customers already love you. Stop renting them from Etsy.",
    lede: "You built something on Etsy. Your reviews are real, your products are handmade, your customers keep coming back. And every year, Etsy takes more. Spotlightly gives you a direct line to the customers who already love your work.",
    pain: "Etsy",
    painDetail: "Etsy charges 6.5% transaction fee + 3% + $0.25 payment processing + $0.20 per listing + 15% for offsite ads above a threshold. A $50 sale costs you $5-10 in fees before materials or shipping.",
    features: [
      { icon: "🛍️", title: "Your own marketplace", desc: "List your handmade items directly. 5% to Spotlightly — not 15%." },
      { icon: "🔒", title: "Subscriber-only drops", desc: "New items available to subscribers 48 hours before anyone else." },
      { icon: "💛", title: "Digital patterns & files", desc: "Knitting patterns, SVG files, crochet guides. 0% cut." },
      { icon: "🎥", title: "Making-of content", desc: "The dyeing process, the glazing session, the craft. Locked for subscribers." },
      { icon: "📡", title: "Live craft sessions", desc: "Stream yourself making. First dibs on what you're creating." },
      { icon: "💌", title: "Direct fan relationships", desc: "Front Row messages — your best customers reach you directly." },
    ],
    earningExample: {
      scenario: "150 subscribers at $7.99/mo + $2,000/mo in marketplace sales",
      them: { platform: "Etsy alone", take: "$300-400/mo in fees on sales", youGet: "$1,600/mo" },
      us: { fee: "$29/mo flat + 5% on sales", youGet: "$3,098/mo" },
    },
    cta: "Claim your maker handle",
    metaTitle: "Spotlightly for Etsy Sellers — Own Your Audience, Cut the Fees",
    metaDesc: "Etsy takes up to 15%. Spotlightly charges flat monthly + 5% on sales. Keep your customers.",
    advisorContext: "This creator is an Etsy seller or handmade goods maker. Their top opportunities: marketplace listings (5% cut vs Etsy's 15%), digital pattern/file sales (0% cut), subscriber-only early access to new products, and behind-the-scenes making content.",
    topFeatures: ["Marketplace (5% vs Etsy's 15%)", "Digital Store (patterns — 0% cut)", "Subscriber early access drops"],
  },
  {
    slug: "woodworkers",
    name: "Woodworkers",
    pageName: "Woodworkers & Craftspeople",
    emoji: "🪵",
    category: "Commerce & Makers",
    headline: "Your craft videos go viral. Your bank account doesn't.",
    subhead: "Turn views into subscribers and subscribers into income.",
    lede: "People watch you work. They share your videos. They ask where to buy your pieces. But YouTube pays you pennies per view and your Etsy shop competes with mass-produced knockoffs. Spotlightly gives your real fans somewhere to actually support you.",
    pain: "YouTube / Etsy",
    painDetail: "YouTube pays $1-5 per 1,000 views on woodworking content. Etsy surfaces mass-produced furniture above your handmade pieces. Your skills are genuinely rare — your income doesn't reflect that.",
    features: [
      { icon: "📁", title: "Sell plans & templates", desc: "Your build plans as PDFs or digital files. 0% cut. Instant download." },
      { icon: "🛍️", title: "Sell finished pieces", desc: "List your handcrafted work directly. No Etsy competition. 5% platform cut." },
      { icon: "🔒", title: "Project build series", desc: "Step-by-step build content locked for subscribers." },
      { icon: "📡", title: "Live workshop sessions", desc: "Stream your builds. Subscribers watch and learn." },
      { icon: "🎥", title: "Technique tutorials", desc: "Joinery, finishing, tool reviews. Your expertise as content." },
      { icon: "💬", title: "Commission requests", desc: "Fans pay to request custom pieces through Front Row messages." },
    ],
    earningExample: {
      scenario: "250 subscribers at $9.99/mo + 100 plan sales at $14.99",
      them: { platform: "YouTube + Etsy", take: "YouTube pays ~$150/mo. Etsy takes 6.5%.", youGet: "$2,638/mo" },
      us: { fee: "$79/mo flat", youGet: "$3,996/mo" },
    },
    cta: "Claim your workshop handle",
    metaTitle: "Spotlightly for Woodworkers — Sell Plans, Build Subscribers, Earn More",
    metaDesc: "YouTube pays pennies. Build a subscriber base, sell your plans directly, and list your handcrafted pieces without Etsy's competition.",
    advisorContext: "This creator is a woodworker or craftsperson. Their top opportunities: selling build plans as digital downloads (0% cut), live workshop streams, step-by-step build content for subscribers, and selling finished pieces in the marketplace.",
    topFeatures: ["Digital Store (build plans — 0% cut)", "Exclusive build series for subscribers", "Marketplace (finished pieces)"],
  },
  {
    slug: "candle-soap-makers",
    name: "Candle & Soap Makers",
    pageName: "Candle & Soap Makers",
    emoji: "🕯️",
    category: "Commerce & Makers",
    headline: "Your scents, your recipes, your business.",
    subhead: "Build a subscriber base that comes back every month.",
    lede: "You make beautiful products. You sell on Etsy, at markets, through your own site. The reorder rate is high — your customers love what you make. But you're rebuilding your customer list from scratch every time. Spotlightly gives you a direct, permanent connection to every customer who loves your work.",
    pain: "Etsy / Farmers Markets",
    painDetail: "Etsy charges 6.5% transaction + listing fees + payment processing. Market booths cost $50-300/day with no guarantee of sales. You're constantly acquiring new customers instead of building relationships with existing ones.",
    features: [
      { icon: "🛍️", title: "Sell directly from your page", desc: "Your products, your prices, your customer relationship. 5% to Spotlightly." },
      { icon: "🔒", title: "Subscriber exclusives", desc: "Limited seasonal scents available only to subscribers first." },
      { icon: "📁", title: "Sell your recipes & formulas", desc: "Your candle and soap recipes as digital products. 0% cut." },
      { icon: "🎥", title: "Making process content", desc: "Pour days, scent blending, packaging. Subscribers see the craft." },
      { icon: "📡", title: "Live pour sessions", desc: "Stream your process. Subscribers watch and often buy immediately after." },
      { icon: "🧶", title: "Custom orders", desc: "Front Row messages for custom scent and batch requests." },
    ],
    earningExample: {
      scenario: "100 subscribers at $9.99/mo + $1,500/mo in marketplace sales",
      them: { platform: "Etsy + markets", take: "Etsy fees + market booth costs", youGet: "$1,200/mo" },
      us: { fee: "$29/mo flat + 5% on sales", youGet: "$2,494/mo" },
    },
    cta: "Claim your maker handle",
    metaTitle: "Spotlightly for Candle & Soap Makers — Sell Directly, Build Subscribers",
    metaDesc: "Stop paying Etsy fees and market booth costs. Build a direct subscriber relationship with customers who love your products.",
    advisorContext: "This creator makes candles, soap, or bath products. Their top opportunities: marketplace listings (5% cut), exclusive subscriber-only seasonal products, recipe/formula digital downloads, and live making content.",
    topFeatures: ["Marketplace (direct sales — 5% cut)", "Exclusive subscriber product drops", "Recipe/formula digital downloads"],
  },
  {
    slug: "jewelry-makers",
    name: "Jewelry Makers",
    pageName: "Jewelry Makers & Designers",
    emoji: "💎",
    category: "Commerce & Makers",
    headline: "Handmade jewelry deserves a handmade audience.",
    subhead: "Your customers are loyal. Give them a home.",
    lede: "Your pieces are one-of-a-kind. The people who buy from you know they're getting something made by a real person. But Etsy buries you under mass-produced jewelry, and Instagram's algorithm decides whether your audience even sees your new pieces. Spotlightly puts you directly in front of the people who already love your work.",
    pain: "Etsy / Instagram",
    painDetail: "Etsy charges 6.5% + payment processing + offsite ad fees you can't always opt out of. Instagram shows your posts to 5-8% of your followers. Your best customers have no easy way to get notified when you drop new pieces.",
    features: [
      { icon: "🛍️", title: "New piece drops", desc: "List your pieces as they're made. Subscribers see them first." },
      { icon: "🔒", title: "Subscriber first access", desc: "24-48 hour head start on new pieces before they go public." },
      { icon: "📁", title: "Making guides & tutorials", desc: "Wire wrapping, stone setting, metalsmithing. 0% cut." },
      { icon: "📡", title: "Live making sessions", desc: "Stream your bench work. Subscribers get first pick of what you make." },
      { icon: "🎥", title: "Behind the design process", desc: "Sketches, inspiration, material sourcing. Locked for subscribers." },
      { icon: "💬", title: "Custom commissions", desc: "Paid priority messages for custom piece requests." },
    ],
    earningExample: {
      scenario: "80 subscribers at $11.99/mo + $1,200/mo in piece sales",
      them: { platform: "Etsy", take: "$120-180/mo in Etsy fees", youGet: "$1,080/mo" },
      us: { fee: "$29/mo flat + 5% on sales", youGet: "$2,099/mo" },
    },
    cta: "Claim your jewelry handle",
    metaTitle: "Spotlightly for Jewelry Makers — Direct Sales, Loyal Subscribers",
    metaDesc: "Stop losing sales to Etsy's fees and algorithm. Build a subscriber base that gets first access to your new pieces.",
    advisorContext: "This creator makes handmade jewelry. Their top opportunities: marketplace drops (5% cut), subscriber first access to new pieces, tutorial/technique digital downloads, and live bench sessions.",
    topFeatures: ["Marketplace (new piece drops)", "Subscriber early access", "Tutorial digital downloads"],
  },

  // ── Education & Knowledge ──────────────────────────────────────
  {
    slug: "authors",
    name: "Authors",
    pageName: "Authors & Writers",
    emoji: "📚",
    category: "Education & Knowledge",
    headline: "Your readers want more than a book every two years.",
    subhead: "Give them the story behind the story.",
    lede: "Your readers finished your book and wanted more. They followed you on social media, but Instagram only shows your posts to 3% of your followers. Your newsletter open rates are dropping. Spotlightly is where your readers come to go deeper.",
    pain: "Substack / Patreon",
    painDetail: "Substack takes 10% of paid subscriptions. Patreon takes 5-12%. Your social media reach is algorithmically throttled. Your email list is owned by a platform that can change its terms anytime.",
    features: [
      { icon: "📖", title: "Exclusive chapters & drafts", desc: "Early chapters, alternate endings, deleted scenes. Subscribers get access first." },
      { icon: "🗂️", title: "Research & world-building", desc: "Maps, character bibles, research notes. Superfan content." },
      { icon: "📁", title: "Digital downloads", desc: "Ebooks, writing guides, companion materials. 0% cut." },
      { icon: "✍️", title: "Signed copies marketplace", desc: "Personalized signed copies. Readers want something that came from you." },
      { icon: "📡", title: "Reader Q&A live streams", desc: "Book club discussions, AMA sessions with your most engaged readers." },
      { icon: "🔒", title: "ARC distribution", desc: "Advance reader copies to subscriber tier before publication." },
    ],
    earningExample: {
      scenario: "500 reader subscribers at $5.99/mo + 100 ebook sales at $9.99",
      them: { platform: "Substack", take: "$299/mo (10% cut)", youGet: "$2,696/mo" },
      us: { fee: "$79/mo flat", youGet: "$2,916/mo" },
    },
    cta: "Claim your author handle",
    metaTitle: "Spotlightly for Authors — Build a Reader Community, Earn Beyond the Book",
    metaDesc: "Your readers want more than a book every two years. Give them exclusive content, early chapters, and a direct connection.",
    advisorContext: "This creator is an author or writer. Their top opportunities: exclusive chapter and draft content for subscribers, digital ebook and guide sales (0% cut), signed copy marketplace listings, and live reader Q&A sessions. Substack takes 10% — Spotlightly is a flat fee.",
    topFeatures: ["Exclusive chapters for subscribers", "Digital Store (ebooks — 0% cut)", "Signed copies marketplace"],
  },
  {
    slug: "educators",
    name: "Educators",
    pageName: "Teachers & Educators",
    emoji: "🎓",
    category: "Education & Knowledge",
    headline: "Your expertise is worth more than free YouTube tutorials.",
    subhead: "Build a paying student base from the audience you already teach.",
    lede: "You make educational content. You post on YouTube, TikTok, Instagram. Tens of thousands of people have learned something real from you for free. A fraction of them would happily pay for deeper access — more structured content, live sessions, downloadable resources. Spotlightly is where that fraction comes to pay you.",
    pain: "YouTube / Teachable",
    painDetail: "YouTube pays $1-5 per 1,000 views. Teachable takes 5% of transactions. Udemy takes 50-75% of every course sale when they run their endless discount promotions that you can't opt out of.",
    features: [
      { icon: "📁", title: "Sell courses & guides", desc: "PDF guides, video courses, worksheets. 0% cut. Instant access." },
      { icon: "🔒", title: "Subscriber-only deep dives", desc: "The content that goes deeper than your free YouTube videos." },
      { icon: "📡", title: "Live tutoring sessions", desc: "Office hours, live workshops, Q&A. Subscribers only." },
      { icon: "🎥", title: "Structured course content", desc: "Multi-part series gated for paying subscribers." },
      { icon: "💬", title: "Student questions", desc: "Front Row messages let students ask specific questions. You decide what to answer." },
      { icon: "🛍️", title: "Study resources marketplace", desc: "Physical study materials, recommended books, toolkits." },
    ],
    earningExample: {
      scenario: "300 subscribers at $9.99/mo + 200 course sales at $49",
      them: { platform: "Udemy", take: "Udemy keeps 50-75% when they run promotions", youGet: "$4,900/mo" },
      us: { fee: "$79/mo flat", youGet: "$12,918/mo" },
    },
    cta: "Claim your educator handle",
    metaTitle: "Spotlightly for Educators — Sell Courses, Build Subscribers, Teach Deeper",
    metaDesc: "Udemy takes 50-75%. YouTube pays pennies. Build a subscriber base of paying students and keep 100% of course sales.",
    advisorContext: "This creator is an educator or teacher. Their top opportunities: selling courses and guides as digital downloads (0% cut), subscriber-only deep-dive content, live office hours and Q&A sessions, and structured multi-part course series for subscribers.",
    topFeatures: ["Digital Store (courses & guides — 0% cut)", "Live teaching sessions", "Subscriber-only deep dives"],
  },
  {
    slug: "language-teachers",
    name: "Language Teachers",
    pageName: "Language Teachers & Tutors",
    emoji: "🌍",
    category: "Education & Knowledge",
    headline: "Your students keep coming back. Make it worth it for you too.",
    subhead: "Build a subscription-based language learning community.",
    lede: "You teach a language on YouTube, TikTok, or Instagram. Your followers are learning from you for free. They'd pay for structured lessons, practice materials, and direct access to you — they just don't have a place to do it directly with you. Spotlightly is that place.",
    pain: "YouTube / italki",
    painDetail: "italki takes 15% of every session. YouTube pays $0.50-2 per 1,000 views on language content. Your students are scattered across platforms with no central place to access your structured content.",
    features: [
      { icon: "📁", title: "Sell lesson packs & workbooks", desc: "Structured learning materials. 0% cut. Instant download." },
      { icon: "🔒", title: "Subscriber-only lessons", desc: "Deeper grammar, vocabulary, and culture content for paying students." },
      { icon: "📡", title: "Live conversation practice", desc: "Group practice sessions, pronunciation coaching, live Q&A." },
      { icon: "🎥", title: "Structured course series", desc: "Beginner to advanced series locked for subscribers." },
      { icon: "💬", title: "Student questions", desc: "Paid priority messages for specific language questions." },
      { icon: "🌍", title: "Culture & travel content", desc: "Language immersion, cultural context, travel guides." },
    ],
    earningExample: {
      scenario: "200 subscribers at $12.99/mo + 100 lesson pack sales at $24.99",
      them: { platform: "italki + YouTube", take: "italki keeps 15%. YouTube pays $1-2/1k views.", youGet: "$3,797/mo" },
      us: { fee: "$79/mo flat", youGet: "$5,097/mo" },
    },
    cta: "Claim your language handle",
    metaTitle: "Spotlightly for Language Teachers — Build a Subscriber Learning Community",
    metaDesc: "italki takes 15%. Build a subscriber base of paying students, sell lesson packs directly, and host live conversation practice.",
    advisorContext: "This creator teaches a language. Their top opportunities: selling lesson packs and workbooks (0% cut), subscriber-only structured course content, live conversation practice and Q&A sessions. italki takes 15% — Spotlightly is a flat fee.",
    topFeatures: ["Digital Store (lesson packs — 0% cut)", "Live conversation sessions", "Subscriber course series"],
  },
  {
    slug: "finance-creators",
    name: "Finance Creators",
    pageName: "Finance & Investing Creators",
    emoji: "📈",
    category: "Education & Knowledge",
    headline: "Your financial advice is worth more than ad revenue.",
    subhead: "Build a subscriber community that pays for real insights.",
    lede: "You teach personal finance, investing, or money management. Your followers have learned genuinely useful things from you. They trust you. They want deeper access — your actual portfolio, your research, your weekly analysis. Spotlightly is where they come to pay for that access.",
    pain: "YouTube / Substack",
    painDetail: "YouTube demonetizes finance content constantly. Substack takes 10%. Your most valuable insights — the ones that could actually move markets or help people make decisions — can't go on public platforms without compliance risk. A private subscriber community changes that.",
    features: [
      { icon: "🔒", title: "Subscriber-only analysis", desc: "Your real research, watchlists, and weekly breakdowns. Gated from public." },
      { icon: "📁", title: "Financial tools & templates", desc: "Spreadsheets, calculators, trackers. 0% cut. Instant download." },
      { icon: "📡", title: "Live market sessions", desc: "Weekly live analysis or Q&A for subscribers." },
      { icon: "📊", title: "Portfolio updates", desc: "What you're actually doing with your money. Subscriber-only." },
      { icon: "💬", title: "Direct questions", desc: "Paid priority messages for specific financial questions." },
      { icon: "🎥", title: "Deep dive content", desc: "Stock analysis, sector breakdowns, macro commentary." },
    ],
    earningExample: {
      scenario: "400 subscribers at $14.99/mo",
      them: { platform: "Substack", take: "$600/mo (10% cut)", youGet: "$5,396/mo" },
      us: { fee: "$79/mo flat", youGet: "$5,917/mo" },
    },
    cta: "Claim your finance handle",
    metaTitle: "Spotlightly for Finance Creators — Build a Paid Subscriber Community",
    metaDesc: "Substack takes 10%. Build a subscriber base for your financial analysis and keep 90% more of what your audience pays you.",
    advisorContext: "This creator covers personal finance or investing. Their top opportunities: subscriber-only analysis and research content, financial templates and tools (0% cut), live market Q&A sessions, and portfolio/watchlist updates for subscribers.",
    topFeatures: ["Subscriber-only analysis content", "Digital Store (financial tools — 0% cut)", "Live market Q&A sessions"],
  },

  // ── Music & Entertainment ──────────────────────────────────────
  {
    slug: "musicians",
    name: "Musicians",
    pageName: "Musicians & Bands",
    emoji: "🎵",
    category: "Music & Entertainment",
    headline: "Streaming pays fractions of a cent. Your fans will pay more.",
    subhead: "The people who actually care about your music want a direct connection to you.",
    lede: "Spotify pays $0.003 per stream. Apple Music pays $0.01. Your real fans — the ones who come to every show, who know every lyric — have nowhere to go to actually support you. Spotlightly is that place.",
    pain: "Spotify / streaming",
    painDetail: "A song needs 250,000 streams to earn $1,000 on Spotify. Artists with 10,000 monthly listeners earn roughly $30-50/month from streaming. The same audience on Spotlightly at $7.99/mo would earn $79,900/mo.",
    features: [
      { icon: "🎵", title: "Exclusive tracks & demos", desc: "Unreleased music, demo recordings, acoustic versions. Subscribers get it first." },
      { icon: "📁", title: "Sell music directly", desc: "Albums, singles, stems, sample packs. 0% cut. No streaming split." },
      { icon: "📡", title: "Live sessions & performances", desc: "Intimate performances for your subscribers only." },
      { icon: "🎥", title: "Studio & recording content", desc: "The writing process, recording sessions, direction changes." },
      { icon: "🛍️", title: "Merch through Loudcap", desc: "Your designs worldwide. No upfront inventory." },
      { icon: "✍️", title: "Signed merch & personal items", desc: "Signed vinyl, handwritten lyrics, instrument picks." },
    ],
    earningExample: {
      scenario: "500 subscribers at $7.99/mo",
      them: { platform: "Spotify", take: "Need 1.3M streams/month to match this", youGet: "$3,995/mo" },
      us: { fee: "$79/mo flat", youGet: "$3,916/mo" },
    },
    cta: "Claim your music handle",
    metaTitle: "Spotlightly for Musicians — Build a Fan Base That Actually Pays",
    metaDesc: "Spotify pays $0.003 per stream. Your fans will pay $7.99/mo for direct access to you.",
    advisorContext: "This creator is a musician or band. Their top opportunities: exclusive tracks and demos for subscribers, selling music directly (0% cut on digital downloads), live intimate performance streams, and studio/recording process content. Spotify pays fractions — Spotlightly is direct.",
    topFeatures: ["Exclusive music for subscribers", "Digital Store (music sales — 0% cut)", "Live performance streams"],
  },
  {
    slug: "podcasters",
    name: "Podcasters",
    pageName: "Podcasters",
    emoji: "🎙️",
    category: "Music & Entertainment",
    headline: "Ad reads at $15 CPM. Subscribers at $7.99/month. Do the math.",
    subhead: "Your listeners are your most loyal audience in media. Get paid like it.",
    lede: "Podcast listeners are the most loyal audience in media. They listen at 1.5x speed for hours. They follow up on everything you recommend. They tell their friends. And most of them would pay directly for ad-free episodes, bonus content, and access to you. Spotlightly is where they come to do that.",
    pain: "Spotify podcasting / ad networks",
    painDetail: "Podcast ad networks pay $15-25 CPM. A podcast with 10,000 listeners earns $150-250 per episode from ads. The same listeners at $7.99/mo would earn $79,900/mo. You're the one building the audience — the ad network collects the margin.",
    features: [
      { icon: "🔒", title: "Ad-free episodes for subscribers", desc: "Same episode, no ads. The single most common reason podcast fans pay." },
      { icon: "🎵", title: "Bonus episodes", desc: "Extended interviews, behind-the-scenes commentary, research deep dives." },
      { icon: "📡", title: "Live recordings", desc: "Stream live episode recordings. Subscribers watch the process." },
      { icon: "📁", title: "Show resources", desc: "Research documents, reading lists, episode transcripts. 0% cut." },
      { icon: "💬", title: "Listener Q&A", desc: "Paid priority questions for episodes. Front Row messages." },
      { icon: "🎥", title: "Video versions & bloopers", desc: "The full video recording, outtakes, pre-show chatter." },
    ],
    earningExample: {
      scenario: "1,000 subscribers at $5.99/mo",
      them: { platform: "Ad networks", take: "10,000 listeners → ~$200/episode from ads", youGet: "$1,600/mo" },
      us: { fee: "$249/mo flat", youGet: "$5,741/mo" },
    },
    cta: "Claim your podcast handle",
    metaTitle: "Spotlightly for Podcasters — Build a Subscriber Base Beyond Ad Revenue",
    metaDesc: "Ad networks pay $15 CPM. Your listeners will pay $5.99/mo for ad-free episodes and bonus content. Build a direct subscriber relationship.",
    advisorContext: "This creator is a podcaster. Their top opportunities: ad-free subscriber episodes, bonus content and extended interviews, live recording streams, and listener Q&A through Front Row messages. Ad CPMs are declining — direct subscriptions are the future.",
    topFeatures: ["Ad-free subscriber episodes", "Bonus episodes & extended content", "Live recording streams"],
  },
  {
    slug: "comedians",
    name: "Comedians",
    pageName: "Comedians & Entertainers",
    emoji: "🎭",
    category: "Music & Entertainment",
    headline: "Viral clips don't pay rent. Your audience can.",
    subhead: "Build a subscriber community that shows up for you.",
    lede: "You go viral on TikTok. 2 million people watch your bit. You make $60. The same 200 real fans who follow everything you do, watch your live sets, and would absolutely pay $8/month for more from you — those 200 people are worth more than 2 million views. Spotlightly is where they go.",
    pain: "TikTok / YouTube",
    painDetail: "TikTok pays $0.02-0.04 per 1,000 views on comedy. A viral 2M view video pays $60-80. YouTube pays $0.50-1.50 per 1,000 views on comedy content. You're creating content that people share for free and you're subsidizing their entertainment.",
    features: [
      { icon: "🎭", title: "Exclusive sets & specials", desc: "Subscriber-only recordings of your sets before they go anywhere else." },
      { icon: "📡", title: "Live shows for subscribers", desc: "Intimate live performances and work-in-progress sets." },
      { icon: "🔒", title: "Behind-the-bit content", desc: "The writing process, bombing stories, the bits that didn't make it." },
      { icon: "🎥", title: "Work in progress content", desc: "Testing new material, workshopping bits, rough drafts." },
      { icon: "📁", title: "Writing resources", desc: "Your joke writing process, structure guides. For fans who also write." },
      { icon: "💬", title: "Fan interaction", desc: "Front Row messages let your biggest fans reach you." },
    ],
    earningExample: {
      scenario: "300 subscribers at $7.99/mo",
      them: { platform: "TikTok viral content", take: "2M views pays ~$70", youGet: "$2,397/mo" },
      us: { fee: "$79/mo flat", youGet: "$2,318/mo" },
    },
    cta: "Claim your comedy handle",
    metaTitle: "Spotlightly for Comedians — Build a Subscriber Base Beyond Viral Clips",
    metaDesc: "A viral 2M view video pays $60. 300 subscribers at $7.99/mo pays $2,397. Build the audience that actually pays you.",
    advisorContext: "This creator is a comedian or entertainer. Their top opportunities: exclusive set recordings for subscribers, live intimate performances, behind-the-bit process content, and work-in-progress material for superfans.",
    topFeatures: ["Exclusive set recordings for subscribers", "Live intimate shows", "Behind-the-bit process content"],
  },
  {
    slug: "djs-producers",
    name: "DJs & Producers",
    pageName: "DJs & Music Producers",
    emoji: "🎧",
    category: "Music & Entertainment",
    headline: "Sample packs on Splice pay you once. Subscribers pay you every month.",
    subhead: "Build a community around your sound.",
    lede: "You make beats. You release sample packs. You DJ. Your SoundCloud followers love your sound but you have no way to monetize that love directly. Spotlightly gives your audience a place to pay you — for your samples, your tutorials, your exclusive mixes.",
    pain: "Splice / SoundCloud",
    painDetail: "Splice pays producers a flat rate or small percentage when their samples are used. SoundCloud's monetization pays fractions of a cent per stream. Your sound is influencing thousands of tracks and you're getting pennies.",
    features: [
      { icon: "📁", title: "Sell sample packs directly", desc: "Your drums, synths, loops. 0% cut. Better than Splice's flat rates." },
      { icon: "🔒", title: "Exclusive subscriber packs", desc: "Monthly exclusive samples only available to subscribers." },
      { icon: "📡", title: "Live production sessions", desc: "Stream your DAW. Show your process. Subscribers watch and learn." },
      { icon: "🎵", title: "Exclusive mixes & sets", desc: "Subscriber-only mixes before they go public." },
      { icon: "🎥", title: "Production tutorials", desc: "Your workflow, sound design techniques, mixing secrets." },
      { icon: "💬", title: "Beat requests", desc: "Paid priority messages for beat commissions." },
    ],
    earningExample: {
      scenario: "200 subscribers at $9.99/mo + 150 sample pack sales at $29",
      them: { platform: "Splice", take: "Splice pays flat rates far below retail", youGet: "$2,348/mo" },
      us: { fee: "$79/mo flat", youGet: "$6,230/mo" },
    },
    cta: "Claim your producer handle",
    metaTitle: "Spotlightly for DJs & Producers — Sell Sample Packs, Build Subscribers",
    metaDesc: "Splice pays flat rates. Sell your sample packs directly at 0% cut and build a subscriber community around your sound.",
    advisorContext: "This creator is a DJ or music producer. Their top opportunities: selling sample packs directly (0% cut), exclusive monthly subscriber packs, live production stream sessions, and production tutorial content.",
    topFeatures: ["Digital Store (sample packs — 0% cut)", "Exclusive monthly subscriber packs", "Live production streams"],
  },

  // ── Health & Lifestyle ─────────────────────────────────────────
  {
    slug: "fitness",
    name: "Fitness Creators",
    pageName: "Fitness & Wellness Creators",
    emoji: "💪",
    category: "Health & Lifestyle",
    headline: "Your followers work out because of you. Get paid for it.",
    subhead: "Every PT, coach, and trainer with an audience should be earning from it.",
    lede: "You post workouts. You share nutrition advice. Your followers get results. TikTok pays you $0.03 per 1,000 views. Meanwhile, your knowledge is genuinely changing people's lives. Spotlightly is where your audience comes to pay you directly.",
    pain: "TikTok / Instagram",
    painDetail: "A fitness video with 500,000 TikTok views pays roughly $15. Instagram pays nothing for Reels unless you're in a limited creator program. Your followers use your free content with no path to becoming paying clients.",
    features: [
      { icon: "📁", title: "Sell training programs", desc: "Your programming as PDFs or video series. 0% cut. Instant access." },
      { icon: "🔒", title: "Subscriber-only workouts", desc: "Daily or weekly content locked for subscribers." },
      { icon: "📡", title: "Live training sessions", desc: "Stream live workouts, form checks, Q&As." },
      { icon: "💬", title: "Check-in messages", desc: "Paid priority messages for form questions and check-ins." },
      { icon: "🛍️", title: "Gear recommendations", desc: "Sell equipment you've tested. Your followers trust your opinion." },
      { icon: "📊", title: "Nutrition guides", desc: "Meal plans, macro guides, recipe books as digital products." },
    ],
    earningExample: {
      scenario: "300 subscribers at $12.99/mo + 200 program sales at $49",
      them: { platform: "Instagram + Patreon", take: "$585+/mo in Patreon fees + $0 from Instagram", youGet: "$9,195/mo" },
      us: { fee: "$79/mo flat", youGet: "$9,701/mo" },
    },
    cta: "Claim your fitness handle",
    metaTitle: "Spotlightly for Fitness Creators — Sell Programs, Build Subscribers, Train Online",
    metaDesc: "Stop earning $0.03 per 1,000 TikTok views. Build a subscriber base, sell your training programs directly, and keep 100% of digital product sales.",
    advisorContext: "This creator makes fitness and wellness content. Their top opportunities: selling training programs (0% cut), subscriber workout content, live training streams, nutrition guides as digital products. Mention that 300 subscribers at $12.99/mo = $3,897/mo.",
    topFeatures: ["Digital Store (programs — 0% cut)", "Subscriber-only workouts", "Live training sessions"],
  },
  {
    slug: "yoga-meditation",
    name: "Yoga & Meditation",
    pageName: "Yoga Teachers & Meditation Guides",
    emoji: "🧘",
    category: "Health & Lifestyle",
    headline: "Your practice deserves to sustain you.",
    subhead: "Build a subscriber community around the calm you create.",
    lede: "You teach yoga or meditation on YouTube, Instagram, or TikTok. Thousands of people start their day with your voice. They find calm in your content. They're loyal in a way most creators never experience. Spotlightly gives them a way to invest in you the way you've invested in them.",
    pain: "YouTube / Insight Timer",
    painDetail: "Insight Timer pays a small flat fee per meditation play. YouTube pays $1-3 per 1,000 views on wellness content. Your audience uses your content daily and most monetization options feel misaligned with the values you teach.",
    features: [
      { icon: "🔒", title: "Daily subscriber practice", desc: "Morning sessions, monthly challenges, exclusive content for your community." },
      { icon: "📁", title: "Guided session downloads", desc: "Your meditations, yoga flows, breathwork sessions as downloadable audio/video. 0% cut." },
      { icon: "📡", title: "Live practice sessions", desc: "Stream live yoga or meditation. Subscribers practice together." },
      { icon: "🎥", title: "Deep practice content", desc: "The philosophy, the lineage, the depth that doesn't fit in a short video." },
      { icon: "💬", title: "Student questions", desc: "Paid priority messages for practice questions and guidance." },
      { icon: "📊", title: "30-day programs", desc: "Structured courses as digital downloads. 0% cut." },
    ],
    earningExample: {
      scenario: "400 subscribers at $9.99/mo",
      them: { platform: "Insight Timer + YouTube", take: "Daily sessions → ~$200/mo total", youGet: "$3,996/mo" },
      us: { fee: "$79/mo flat", youGet: "$3,917/mo" },
    },
    cta: "Claim your practice handle",
    metaTitle: "Spotlightly for Yoga Teachers — Build a Subscriber Practice Community",
    metaDesc: "Insight Timer pays fractions. Build a subscriber community that sustains your practice, and sell your guided sessions directly at 0% cut.",
    advisorContext: "This creator teaches yoga or meditation. Their top opportunities: subscriber daily practice content, downloadable guided sessions (0% cut), live practice streams, and structured 30-day program courses.",
    topFeatures: ["Daily subscriber practice content", "Guided session downloads (0% cut)", "Live practice streams"],
  },
  {
    slug: "chefs-cooks",
    name: "Chefs & Cooks",
    pageName: "Chefs, Cooks & Food Creators",
    emoji: "👨‍🍳",
    category: "Health & Lifestyle",
    headline: "Your recipes are your best product. Sell them.",
    subhead: "Your food followers are hungry for more. Give them access.",
    lede: "You share recipes on TikTok, Instagram, and YouTube. Millions of people cook your food. They screenshot your videos and remake your dishes. They'd happily pay for your full recipe collection, your techniques, your exclusive content. Spotlightly is where they come to support you.",
    pain: "TikTok / food blogs",
    painDetail: "TikTok pays $0.02-0.04 per 1,000 views. Food blogs make money through ad networks that require 100,000+ monthly pageviews to get approved. Recipe platforms take 30-40% of any digital product sales. Your audience is huge and your monetization is minimal.",
    features: [
      { icon: "📁", title: "Sell recipe books & collections", desc: "Your full recipe collections as PDFs. 0% cut. Instant download." },
      { icon: "🔒", title: "Subscriber-only recipes", desc: "Your best recipes and techniques locked for paying subscribers." },
      { icon: "📡", title: "Live cooking classes", desc: "Cook together in real time. Subscribers join live." },
      { icon: "🎥", title: "Technique deep dives", desc: "The knife skills, the knife cuts, the mother sauces. Deep content for serious cooks." },
      { icon: "🛍️", title: "Recommended tools", desc: "The actual tools you use in your kitchen. Your marketplace." },
      { icon: "🧑‍🍳", title: "Meal planning content", desc: "Weekly meal plans, shopping lists, prep guides for subscribers." },
    ],
    earningExample: {
      scenario: "250 subscribers at $8.99/mo + 300 recipe book sales at $19",
      them: { platform: "TikTok + food blog ads", take: "TikTok pays $6-10 per million views. Ad networks require huge traffic.", youGet: "$7,947/mo" },
      us: { fee: "$79/mo flat", youGet: "$7,568/mo" },
    },
    cta: "Claim your kitchen handle",
    metaTitle: "Spotlightly for Food Creators — Sell Recipes, Build Subscribers, Cook Together",
    metaDesc: "TikTok pays $0.03 per 1,000 views. Sell your recipe collections directly at 0% cut and build a subscriber cooking community.",
    advisorContext: "This creator makes food and cooking content. Their top opportunities: selling recipe books and collections (0% cut), subscriber-only exclusive recipes, live cooking class streams, and technique deep-dive content.",
    topFeatures: ["Digital Store (recipe books — 0% cut)", "Subscriber-only recipes", "Live cooking classes"],
  },

  // ── Gaming & Tech ──────────────────────────────────────────────
  {
    slug: "gamers",
    name: "Gamers",
    pageName: "Gamers & Game Streamers",
    emoji: "🎮",
    category: "Gaming & Tech",
    headline: "Twitch takes 50%. Your subscribers pay you directly.",
    subhead: "Build your community where the money goes to you.",
    lede: "You stream. You make YouTube content. You build a community around the games you play. Twitch takes 50% of your subscriptions. YouTube's gaming revenue is unpredictable. Spotlightly is where your core community pays you directly — no platform cut on subscriber revenue.",
    pain: "Twitch / YouTube Gaming",
    painDetail: "Twitch takes 50% of subscription revenue (70/30 only for top partners). YouTube Gaming monetization requires 1,000 subscribers and 4,000 watch hours before you earn anything. Ad CPMs for gaming content are volatile.",
    features: [
      { icon: "🎮", title: "Subscriber community", desc: "Your core fanbase in one place. Monthly subscription — 0% cut to Spotlightly." },
      { icon: "🔒", title: "Exclusive content & VODs", desc: "Videos, analysis, highlights that only subscribers see." },
      { icon: "📡", title: "Private streams", desc: "Subscriber-only streams — more intimate, less toxic." },
      { icon: "📁", title: "Game guides & resources", desc: "Your tier lists, build guides, walkthroughs. 0% cut." },
      { icon: "🛍️", title: "Gaming merch via Loudcap", desc: "Your branding on gear. No upfront cost." },
      { icon: "💬", title: "Game sessions", desc: "Fans pay to join your game session. Front Row access." },
    ],
    earningExample: {
      scenario: "500 subscribers at $6.99/mo",
      them: { platform: "Twitch", take: "Twitch keeps 50% = $1,747/mo", youGet: "$1,748/mo" },
      us: { fee: "$79/mo flat", youGet: "$3,416/mo" },
    },
    cta: "Claim your gaming handle",
    metaTitle: "Spotlightly for Gamers — Build a Subscriber Community, Keep 100%",
    metaDesc: "Twitch takes 50% of subscriptions. Spotlightly charges a flat fee. Keep what your community pays you.",
    advisorContext: "This creator is a gamer or game streamer. Their top opportunities: subscriber community with 0% cut on subscription revenue, private subscriber-only streams, game guides as digital downloads, and merch through Loudcap. Twitch takes 50% — Spotlightly doesn't take a cut of subscription revenue.",
    topFeatures: ["Subscriber community (0% cut)", "Private subscriber-only streams", "Game guides & resources (0% cut)"],
  },
  {
    slug: "tech-creators",
    name: "Tech Creators",
    pageName: "Tech Creators & Developers",
    emoji: "💻",
    category: "Gaming & Tech",
    headline: "Your tutorials are worth more than YouTube ad revenue.",
    subhead: "Your audience builds things because of you. Get paid for it.",
    lede: "You make tutorials. You review tools. You explain complex tech concepts clearly. Your audience learns real skills from you for free. A fraction of them would pay for deeper access — advanced courses, live sessions, direct help. Spotlightly is where that happens.",
    pain: "YouTube / Udemy",
    painDetail: "Udemy runs constant 90% off sales you can't opt out of, turning your $99 course into a $9 impulse buy. YouTube gaming pays $2-5 per 1,000 views on tech content. Your expertise is worth significantly more than what these platforms pay.",
    features: [
      { icon: "📁", title: "Sell courses & tutorials", desc: "Your full course content. 0% cut. No Udemy discount sales." },
      { icon: "🔒", title: "Subscriber deep dives", desc: "Advanced content that goes beyond your free tutorials." },
      { icon: "📡", title: "Live coding sessions", desc: "Build in real time. Subscribers follow along and ask questions." },
      { icon: "🛠️", title: "Templates & starter packs", desc: "Your boilerplate code, config files, workflows. 0% cut." },
      { icon: "💬", title: "Code reviews", desc: "Paid priority messages for specific technical questions." },
      { icon: "🎥", title: "Tool reviews & comparisons", desc: "Deeper analysis locked for subscribers." },
    ],
    earningExample: {
      scenario: "300 subscribers at $12.99/mo + 150 course sales at $79",
      them: { platform: "Udemy", take: "Udemy keeps 50-75% during promotions", youGet: "$5,822/mo" },
      us: { fee: "$79/mo flat", youGet: "$15,648/mo" },
    },
    cta: "Claim your tech handle",
    metaTitle: "Spotlightly for Tech Creators — Sell Courses at Full Price, Build Subscribers",
    metaDesc: "Udemy takes 50-75% during promotions. Sell your tech courses directly at full price and build a subscriber community.",
    advisorContext: "This creator makes tech tutorials or developer content. Their top opportunities: selling courses and tutorials (0% cut, no forced discount sales), subscriber deep-dive content, live coding sessions, and code template/starter pack digital downloads.",
    topFeatures: ["Digital Store (courses — 0% cut, no discounting)", "Live coding sessions", "Subscriber advanced content"],
  },

  // ── Lifestyle & Personal ───────────────────────────────────────
  {
    slug: "travel-creators",
    name: "Travel Creators",
    pageName: "Travel Creators",
    emoji: "✈️",
    category: "Lifestyle & Personal",
    headline: "Brand deals are unpredictable. Subscribers aren't.",
    subhead: "Build recurring income from the audience that lives vicariously through you.",
    lede: "You travel. You document it. You've built an audience that follows your every trip. Brand deals come and go — one month you're flush, the next month there's nothing. Spotlightly gives you a recurring revenue base that doesn't depend on any brand's budget.",
    pain: "Brand deals / YouTube",
    painDetail: "Brand deals average $1,000-5,000 per post depending on audience size — but they're inconsistent, require negotiation, and can be cancelled. YouTube travel content earns $2-5 per 1,000 views. The feast-or-famine cycle is unsustainable.",
    features: [
      { icon: "🔒", title: "Subscriber travel guides", desc: "Your actual guides — where you stayed, ate, got in for free. Locked for subscribers." },
      { icon: "📁", title: "Sell detailed itineraries", desc: "The trip planning documents your followers beg for. 0% cut." },
      { icon: "📡", title: "Live travel streams", desc: "Stream from wherever you are. Subscribers travel with you." },
      { icon: "🎥", title: "Unfiltered content", desc: "The real experience — delays, scams, misses. Subscribers only." },
      { icon: "🗺️", title: "Location research packs", desc: "Your research, tips, and contacts for specific destinations." },
      { icon: "💬", title: "Trip planning help", desc: "Paid priority messages for destination-specific questions." },
    ],
    earningExample: {
      scenario: "500 subscribers at $8.99/mo + 200 itinerary sales at $24",
      them: { platform: "Brand deals + YouTube", take: "Brand deals are inconsistent. YouTube pays $3-5/1k views.", youGet: "$5,000/mo (good months)" },
      us: { fee: "$79/mo flat", youGet: "$9,275/mo (every month)" },
    },
    cta: "Claim your travel handle",
    metaTitle: "Spotlightly for Travel Creators — Build Recurring Income Beyond Brand Deals",
    metaDesc: "Brand deals are inconsistent. Build a subscriber base that pays you every month regardless of what brands are doing with their budgets.",
    advisorContext: "This creator makes travel content. Their top opportunities: subscriber-only detailed travel guides, selling itineraries and location research packs (0% cut), live streams from their travels, and destination-specific Q&A through Front Row messages.",
    topFeatures: ["Subscriber travel guides", "Digital Store (itineraries — 0% cut)", "Live travel streams"],
  },
  {
    slug: "beauty-creators",
    name: "Beauty Creators",
    pageName: "Beauty & Makeup Creators",
    emoji: "💄",
    category: "Lifestyle & Personal",
    headline: "Your tutorials are worth more than $0.03 per 1,000 views.",
    subhead: "Your followers trust your recommendations. Build income around that trust.",
    lede: "You do makeup tutorials. You review skincare. Your followers buy what you recommend. They trust you more than any brand. And TikTok pays you $0.03 per 1,000 views while brands use your credibility to sell products you'll never see another dollar from. Spotlightly changes that.",
    pain: "TikTok / brand deals",
    painDetail: "TikTok beauty content pays $0.02-0.04 per 1,000 views. Brand deals are inconsistent. Most creators are locked into exclusivity clauses that prevent them from working with competitors. Your audience's trust is your most valuable asset — protect it.",
    features: [
      { icon: "📁", title: "Sell your routines & guides", desc: "Your full skincare routine, makeup tutorials, product guides. 0% cut." },
      { icon: "🔒", title: "Subscriber-only tutorials", desc: "The detailed, step-by-step content that doesn't fit in a 60-second video." },
      { icon: "📡", title: "Live beauty sessions", desc: "Stream your full glam. Subscribers watch and ask questions." },
      { icon: "🎥", title: "Honest reviews", desc: "Unsponsored, no-brand-deal honest reviews. Locked for subscribers." },
      { icon: "🛍️", title: "Curated product drops", desc: "Your actual recommendations in your marketplace." },
      { icon: "💬", title: "Personalized advice", desc: "Paid priority messages for skin type and routine questions." },
    ],
    earningExample: {
      scenario: "400 subscribers at $8.99/mo",
      them: { platform: "TikTok + brand deals", take: "Brand deals are inconsistent. TikTok pays fractions.", youGet: "$2,000/mo (inconsistent)" },
      us: { fee: "$79/mo flat", youGet: "$3,517/mo (every month)" },
    },
    cta: "Claim your beauty handle",
    metaTitle: "Spotlightly for Beauty Creators — Build Recurring Income From Your Audience",
    metaDesc: "TikTok pays $0.03 per 1,000 views. Brand deals are inconsistent. Build a subscriber base that pays you every month.",
    advisorContext: "This creator makes beauty and makeup content. Their top opportunities: subscriber-only detailed tutorials, selling routine guides and product guides (0% cut), live beauty session streams, and honest unsponsored reviews for subscribers.",
    topFeatures: ["Subscriber-only detailed tutorials", "Routine & guide digital downloads (0% cut)", "Live beauty sessions"],
  },
  {
    slug: "fashion-creators",
    name: "Fashion Creators",
    pageName: "Fashion & Style Creators",
    emoji: "👗",
    category: "Lifestyle & Personal",
    headline: "Your eye for style should pay you more than affiliate links.",
    subhead: "Build a subscriber community around your taste.",
    lede: "You make fashion content. You style outfits, review trends, build looks. Your followers buy what you show them — affiliate links can prove that. But affiliate commissions are tiny and inconsistent. Spotlightly gives your most devoted followers a direct way to pay for your taste and your access to you.",
    pain: "LTK / affiliate networks",
    painDetail: "LTK pays 1-10% affiliate commissions. If your followers spend $10,000 based on your recommendations, you earn $100-1,000. Meanwhile, those same followers would pay $8.99/month to see your hauls before anyone else and get your unfiltered opinions.",
    features: [
      { icon: "🔒", title: "Subscriber hauls & reviews", desc: "See your hauls first. Unfiltered, no brand deal required." },
      { icon: "📁", title: "Style guides & lookbooks", desc: "Your capsule wardrobes, seasonal guides, fit formulas. 0% cut." },
      { icon: "📡", title: "Live styling sessions", desc: "Stream outfit building, shopping trips, closet edits." },
      { icon: "🛍️", title: "Curated marketplace pieces", desc: "Your personal items when you cycle them out. Vintage, limited pieces." },
      { icon: "🎥", title: "Personal shopping content", desc: "Your actual shopping process. Subscribers see your real opinions." },
      { icon: "💬", title: "Style questions", desc: "Paid priority messages for outfit and shopping advice." },
    ],
    earningExample: {
      scenario: "300 subscribers at $8.99/mo + 100 style guide sales at $29",
      them: { platform: "LTK / affiliate", take: "Followers spend $30,000 → you earn $600", youGet: "$600/mo" },
      us: { fee: "$79/mo flat", youGet: "$5,618/mo" },
    },
    cta: "Claim your style handle",
    metaTitle: "Spotlightly for Fashion Creators — Build Subscribers Beyond Affiliate Links",
    metaDesc: "Affiliate commissions pay 1-10%. Build a subscriber community that pays you directly for your style and access.",
    advisorContext: "This creator makes fashion and style content. Their top opportunities: subscriber-first hauls and reviews, style guide and lookbook digital downloads (0% cut), live styling streams, and vintage/personal piece marketplace listings.",
    topFeatures: ["Subscriber-first hauls & reviews", "Style guide digital downloads (0% cut)", "Personal piece marketplace"],
  },
  {
    slug: "sports-athletes",
    name: "Athletes",
    pageName: "Athletes & Sports Creators",
    emoji: "🏆",
    category: "Lifestyle & Personal",
    headline: "Your training is your content. Your audience wants access to it.",
    subhead: "Build a subscriber base around your athletic journey.",
    lede: "You're an athlete. You train, compete, document it. Your followers are genuinely inspired by what you do. They want training plans, diet insights, the mental game — not just the highlight reel. Spotlightly gives your most devoted fans direct access to all of it.",
    pain: "Instagram / YouTube",
    painDetail: "Instagram shows your posts to 5-8% of your followers. YouTube pays $0.50-2 per 1,000 views on sports content. Your training and performance are compelling content — but the platforms are capturing all the value from the audience you built.",
    features: [
      { icon: "📁", title: "Sell training programs", desc: "Your exact programming. 0% cut. Instant download." },
      { icon: "🔒", title: "Training diary for subscribers", desc: "Daily training, nutrition, recovery — the full picture." },
      { icon: "📡", title: "Live training sessions", desc: "Train together. Subscribers follow your sessions." },
      { icon: "🎥", title: "Competition prep content", desc: "The buildup, the weight cut, the mental prep. Subscribers only." },
      { icon: "🛍️", title: "Gear recommendations", desc: "The equipment you actually use. Your marketplace." },
      { icon: "💬", title: "Training questions", desc: "Paid priority messages for programming and performance questions." },
    ],
    earningExample: {
      scenario: "200 subscribers at $14.99/mo + 150 program sales at $49",
      them: { platform: "Instagram + YouTube", take: "Instagram pays $0. YouTube pays ~$100/mo.", youGet: "$7,450/mo" },
      us: { fee: "$79/mo flat", youGet: "$10,270/mo" },
    },
    cta: "Claim your athlete handle",
    metaTitle: "Spotlightly for Athletes — Build a Subscriber Training Community",
    metaDesc: "Instagram pays nothing. YouTube pays pennies. Build a subscriber community around your training and sell your programs directly.",
    advisorContext: "This creator is an athlete or sports creator. Their top opportunities: selling training programs (0% cut), subscriber daily training diary content, live training sessions, and competition prep content for subscribers.",
    topFeatures: ["Training programs (0% cut)", "Subscriber training diary", "Live training sessions"],
  },

  // ── Parenting & Home ───────────────────────────────────────────
  {
    slug: "parenting-creators",
    name: "Parenting Creators",
    pageName: "Parenting & Family Creators",
    emoji: "👨‍👩‍👧",
    category: "Parenting & Home",
    headline: "Your parenting experience is genuinely helpful. Get paid for it.",
    subhead: "Build a subscriber community of parents who trust your advice.",
    lede: "You share your parenting journey. Other parents find it genuinely helpful — your routines, your honest takes, your systems that actually work. They follow you on Instagram but there's no easy way for them to pay you for the deeper content. Spotlightly changes that.",
    pain: "Instagram / YouTube",
    painDetail: "Parenting content on YouTube earns $2-5 per 1,000 views. Instagram shows your posts to 5-8% of followers. Brand deals for parenting creators pay well but are inconsistent and often require content that feels inauthentic.",
    features: [
      { icon: "📁", title: "Sell parenting guides", desc: "Your sleep training method, your meal prep system, your routine guides. 0% cut." },
      { icon: "🔒", title: "Subscriber-only real talk", desc: "The unfiltered reality of parenting. No brand deal filters." },
      { icon: "📡", title: "Live Q&A sessions", desc: "Ask-me-anything sessions with parents in similar stages." },
      { icon: "🎥", title: "Deep dive parenting content", desc: "The strategies, the research, the things that actually helped." },
      { icon: "💬", title: "Parent questions", desc: "Paid priority messages for specific parenting challenges." },
      { icon: "🛍️", title: "Product recommendations", desc: "The actual products you use and love. Your marketplace." },
    ],
    earningExample: {
      scenario: "300 subscribers at $7.99/mo + 200 guide sales at $19",
      them: { platform: "YouTube + brand deals", take: "Brand deals inconsistent. YouTube pays $3/1k views.", youGet: "$1,000-3,000/mo (varies)" },
      us: { fee: "$79/mo flat", youGet: "$6,177/mo (consistent)" },
    },
    cta: "Claim your parenting handle",
    metaTitle: "Spotlightly for Parenting Creators — Build a Subscriber Community of Parents",
    metaDesc: "Brand deals are inconsistent. Build a subscriber community of parents who trust your advice and pay you directly.",
    advisorContext: "This creator makes parenting content. Their top opportunities: selling parenting guides and system documents (0% cut), subscriber-only real honest content, live Q&A sessions with parent communities, and product recommendation marketplace listings.",
    topFeatures: ["Parenting guides (0% cut)", "Subscriber honest content", "Live parent Q&A sessions"],
  },
  {
    slug: "home-diy",
    name: "Home & DIY",
    pageName: "Home Improvement & DIY Creators",
    emoji: "🔨",
    category: "Parenting & Home",
    headline: "Your home projects inspire millions. Get paid for the blueprints.",
    subhead: "Turn your renovation content into recurring revenue.",
    lede: "You renovate, you DIY, you transform spaces. Your time-lapses go viral. Your before-and-afters get thousands of saves. But your income is ad revenue and brand deals — both inconsistent. Your most engaged followers would pay for your project plans, your supplier contacts, and your step-by-step process. Spotlightly is where that happens.",
    pain: "YouTube / Instagram",
    painDetail: "Home improvement YouTube content earns $3-8 per 1,000 views. Instagram shows your content to 5-8% of followers. Home brand deals are seasonal and budget-dependent. Your most expensive productions — full room renovations — often earn the least per hour invested.",
    features: [
      { icon: "📁", title: "Sell project plans", desc: "Your renovation plans, material lists, step-by-step guides. 0% cut." },
      { icon: "🔒", title: "Subscriber project diaries", desc: "Full progress documentation from demo to reveal. Subscribers get the whole story." },
      { icon: "📡", title: "Live project sessions", desc: "Stream your builds. Subscribers watch and ask questions." },
      { icon: "🛍️", title: "Sourcing guides", desc: "Your supplier contacts, discount codes, product recommendations." },
      { icon: "🎥", title: "Technical tutorials", desc: "Tiling, electrical basics, plumbing walkthroughs. Subscriber-only depth." },
      { icon: "💬", title: "Project advice", desc: "Paid priority messages for specific project questions." },
    ],
    earningExample: {
      scenario: "300 subscribers at $11.99/mo + 200 plan sales at $29",
      them: { platform: "YouTube + home brands", take: "YouTube pays $5-8/1k views on home content", youGet: "$2,000-4,000/mo" },
      us: { fee: "$79/mo flat", youGet: "$9,378/mo" },
    },
    cta: "Claim your DIY handle",
    metaTitle: "Spotlightly for Home & DIY Creators — Sell Plans, Build Subscribers",
    metaDesc: "Your renovation videos go viral. Sell your project plans directly at 0% cut and build a subscriber community that follows every project.",
    advisorContext: "This creator makes home improvement or DIY content. Their top opportunities: selling project plans and material lists (0% cut), subscriber-only project documentation, live build streams, and sourcing guide digital products.",
    topFeatures: ["Project plan digital downloads (0% cut)", "Subscriber project documentation", "Live build streams"],
  },
  {
    slug: "gardening",
    name: "Gardeners",
    pageName: "Gardeners & Plant Creators",
    emoji: "🌱",
    category: "Parenting & Home",
    headline: "Your green thumb built an audience. Time to harvest.",
    subhead: "Your plant knowledge is genuinely rare. Your followers know it.",
    lede: "You grow things. You teach others to grow things. Your plant identification videos get thousands of questions. Your garden design content inspires people to completely change their outdoor spaces. Your audience follows you for knowledge they can't easily find anywhere else. Spotlightly gives them a way to pay you for it.",
    pain: "YouTube / Instagram",
    painDetail: "Gardening YouTube content earns $2-5 per 1,000 views. Instagram gardening content is popular but monetization is almost non-existent. Seasonal brand deals from seed companies and tool brands are inconsistent and low-paying.",
    features: [
      { icon: "📁", title: "Sell growing guides", desc: "Your planting calendars, growing guides, garden design plans. 0% cut." },
      { icon: "🔒", title: "Seasonal subscriber content", desc: "What to plant now, what to harvest, what to prepare — month by month." },
      { icon: "📡", title: "Live garden tours", desc: "Stream your garden. Subscribers see what's growing and ask questions." },
      { icon: "🌱", title: "Plant care deep dives", desc: "Specific plant care content locked for subscribers." },
      { icon: "🛍️", title: "Seeds & tools marketplace", desc: "Your saved seeds, favorite tools, recommended varieties." },
      { icon: "💬", title: "Plant questions", desc: "Paid priority messages for specific growing challenges." },
    ],
    earningExample: {
      scenario: "200 subscribers at $8.99/mo + 150 guide sales at $19",
      them: { platform: "YouTube + seed brands", take: "YouTube pays $2-4/1k views. Seed brand deals are seasonal.", youGet: "$500-1,000/mo" },
      us: { fee: "$29/mo flat", youGet: "$4,629/mo" },
    },
    cta: "Claim your garden handle",
    metaTitle: "Spotlightly for Gardeners — Sell Growing Guides, Build a Plant Community",
    metaDesc: "Your plant knowledge is rare. Sell your growing guides directly at 0% cut and build a subscriber community around your garden.",
    advisorContext: "This creator makes gardening and plant content. Their top opportunities: selling growing guides and planting calendars (0% cut), subscriber seasonal content, live garden tour streams, and marketplace listings for seeds and tools.",
    topFeatures: ["Growing guide digital downloads (0% cut)", "Subscriber seasonal content", "Live garden tours"],
  },
];

export default NICHES;

export function getNiche(slug: string): Niche | undefined {
  return NICHES.find(n => n.slug === slug);
}

export function getAllNicheSlugs(): string[] {
  return NICHES.map(n => n.slug);
}

export function getNichesByCategory(): Record<string, Niche[]> {
  const groups: Record<string, Niche[]> = {};
  for (const n of NICHES) {
    if (!groups[n.category]) groups[n.category] = [];
    groups[n.category].push(n);
  }
  return groups;
}
